/**
 * Menu Pack — Wave B5 of the empowerment plan.
 *
 * The "missing primitive" the UX agent named in Phase 2: one click,
 * all artifacts. Operators stop downloading 5 files and figuring out
 * what to do with each. They get a single .zip whose README.md walks
 * the print shop, the web dev, and the front-of-house staff through
 * what to use and how — in plain English.
 *
 * Privacy posture: pure orchestration. The pack module composes
 * existing emitter outputs (PDF, HTML, JSON-LD, plain text, Markdown)
 * into a ZIP via the same JSZip the QR-menu emitter already lazy-
 * loaded. It does NOT introduce new network calls. Logos travel as
 * data-URLs already embedded in PDF + HTML; never lifted out.
 *
 * Architecture: takes a v3 canonical menu (or a v2 row-stream that it
 * migrates) plus references to the emitter modules. Returns a Promise
 * resolving to a Blob the caller downloads. The pack module owns:
 *   - the README.md authoring (operator-tone, printer + web dev + staff)
 *   - the mailto template authoring
 *   - the manifest.json (machine-readable index)
 *   - the file-naming convention
 *
 * It does NOT own the emitters themselves — those stay in their
 * homes (menu-render-pdf.js / menu-render-html.js / menu-render-text.js
 * / menu-renderers/jsonld.js). Loose coupling so the pack module
 * stays light and testable.
 *
 * UMD-ish loader: attaches MD_PACK on window in browser; exports via
 * module.exports in Node tests.
 */
(function (root) {
  'use strict';

  // ---------- file-naming convention -----------------------------
  // Operator-friendly filenames. Stable so re-exports replace cleanly
  // in the operator's downloads folder.
  function makeSlug(name) {
    return String(name || 'menu')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'menu';
  }

  // ---------- README.md authoring ---------------------------------
  // Plain-English handoff guide. Three audiences: print shop,
  // web dev, front-of-house staff. Each gets a section. Operator
  // tone — no jargon without a one-line definition.
  function buildReadmeEN(opts) {
    var biz = (opts.businessName || 'your restaurant');
    var when = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    var hasPdf = !!opts.includePdf;
    var hasQr = !!opts.includeQr;
    var hasJsonld = !!opts.includeJsonld;
    var hasText = !!opts.includeText;
    var hasMd = !!opts.includeMarkdown;
    var hasMailto = !!opts.includeMailto;
    var pdfName = opts.pdfName || 'menu.pdf';
    var qrName = opts.qrFolder || 'qr-menu/';
    var ldName = opts.jsonldName || 'menu.jsonld';
    var textName = opts.textName || 'menu.txt';
    var mdName = opts.mdName || 'menu.md';
    var mailName = opts.mailtoName || 'mailto-printer.txt';
    var lines = [];
    lines.push('# Menu pack — ' + biz);
    lines.push('');
    lines.push('Generated by **Muntin Menu Design Suite** on ' + when + '.');
    lines.push('');
    lines.push('This folder is everything you need to ship your menu —');
    lines.push('to your printer, to your website, and to your staff. ');
    lines.push('Read the section that matches your role.');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## For your print shop');
    lines.push('');
    if (hasPdf) {
      lines.push('Send them **`' + pdfName + '`**. That is the menu, formatted for ');
      lines.push('print, with crop marks and a 3 mm bleed where supported. They will');
      lines.push('know what to do with it. If they ask about color profile, the answer');
      lines.push('is CMYK; about paper, uncoated cream stock (60–80 lb / 90–120 gsm) ');
      lines.push('reads best on most of our themes. There is a pre-written email at');
      hasMailto
        ? lines.push('**`' + mailName + '`** you can copy-paste.')
        : lines.push('the bottom of this README you can copy-paste.');
    } else {
      lines.push('No print PDF was included in this pack — re-export with the PDF');
      lines.push('button enabled if you need one.');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## For your web developer (or whoever maintains your site)');
    lines.push('');
    if (hasQr) {
      lines.push('Drop the **`' + qrName + '`** folder into your hosting root. The');
      lines.push('`index.html` is self-contained — no scripts, no fetches, all CSS');
      lines.push('inlined. Works on Squarespace (Code Block / File upload), WordPress');
      lines.push('(Media Library / custom HTML), Wix, Shopify, GitHub Pages, anywhere.');
      lines.push('');
      lines.push('The HTML carries valid `schema.org/Menu` JSON-LD in `<head>`. Google');
      lines.push('and Apple Maps will see your dish names, prices, and dietary tags');
      lines.push('without you doing anything else.');
      lines.push('');
      lines.push('Inside the same folder, **`menu-qr.png`** is a 480 × 480 px QR code');
      lines.push('pointing wherever you told us your menu would live. Print it at');
      lines.push('any size from 1" to 6" — QR has built-in error correction.');
    }
    if (hasJsonld) {
      lines.push('');
      lines.push('If your CMS only takes a JSON-LD snippet, **`' + ldName + '`** is');
      lines.push('the same `Menu` graph as a standalone file — paste it inside a');
      lines.push('`<script type="application/ld+json">…</script>` tag in `<head>`.');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## For your staff');
    lines.push('');
    if (hasText) {
      lines.push('**`' + textName + '`** is the menu as plain text — readable in any');
      lines.push('email client, any phone, any printer. Useful as a back-of-house');
      lines.push('reference, a runner sheet, or an inbox copy when the printed menu');
      lines.push('is at the framer.');
    }
    if (hasMd) {
      lines.push('');
      lines.push('**`' + mdName + '`** is the same content as Markdown — pastes into');
      lines.push('Notion, Slack, GitHub, or your training documents without losing');
      lines.push('the structure.');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Save this folder');
    lines.push('');
    lines.push('Tuck the whole zip into a "Menus" folder somewhere safe. Next time');
    lines.push('you reprint, you will not have to start from scratch — your printer');
    lines.push('can re-run the same PDF, and your web dev can re-paste the same HTML.');
    lines.push('');
    lines.push('When you change a price, re-open the tool, edit, and re-export this');
    lines.push('pack. It will overwrite the old files in your downloads folder if');
    lines.push('you keep the same business name.');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('Made with ♥ by Muntin Digital · Silver Spring, MD · muntin.digital');
    return lines.join('\n');
  }

  function buildReadmeES(opts) {
    var biz = (opts.businessName || 'tu restaurante');
    var when = new Date().toLocaleDateString('es-MX', { year: 'numeric', month: 'long', day: 'numeric' });
    var hasPdf = !!opts.includePdf;
    var hasQr = !!opts.includeQr;
    var hasJsonld = !!opts.includeJsonld;
    var hasText = !!opts.includeText;
    var hasMd = !!opts.includeMarkdown;
    var hasMailto = !!opts.includeMailto;
    var pdfName = opts.pdfName || 'menu.pdf';
    var qrName = opts.qrFolder || 'qr-menu/';
    var ldName = opts.jsonldName || 'menu.jsonld';
    var textName = opts.textName || 'menu.txt';
    var mdName = opts.mdName || 'menu.md';
    var mailName = opts.mailtoName || 'mailto-printer.txt';
    var lines = [];
    lines.push('# Pack del menú — ' + biz);
    lines.push('');
    lines.push('Generado por **Muntin Suite de Diseño de Menú** el ' + when + '.');
    lines.push('');
    lines.push('Esta carpeta es todo lo que necesitas para enviar tu menú —');
    lines.push('al impresor, al sitio web y al staff. Lee la sección que');
    lines.push('corresponda a tu rol.');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Para tu imprenta');
    lines.push('');
    if (hasPdf) {
      lines.push('Envíales **`' + pdfName + '`**. Es el menú, formateado para imprenta,');
      lines.push('con marcas de corte y bleed de 3 mm donde aplica. Sabrán qué hacer.');
      lines.push('Si preguntan por perfil de color: CMYK. Por papel: stock uncoated');
      lines.push('crema (60–80 lb / 90–120 gsm) se lee bien en la mayoría de los temas.');
      hasMailto && lines.push('Hay un correo pre-escrito en **`' + mailName + '`** que puedes copiar.');
    } else {
      lines.push('No se incluyó PDF imprimible en este pack — re-exporta con el botón');
      lines.push('de PDF habilitado si lo necesitas.');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Para tu encargado de sitio web');
    lines.push('');
    if (hasQr) {
      lines.push('Coloca la carpeta **`' + qrName + '`** en la raíz de tu hosting. El');
      lines.push('`index.html` es auto-contenido — sin scripts externos, sin fetches,');
      lines.push('todo CSS embebido. Funciona en Squarespace, WordPress, Wix,');
      lines.push('Shopify, GitHub Pages, donde sea.');
      lines.push('');
      lines.push('El HTML lleva JSON-LD `schema.org/Menu` válido en `<head>`. Google y');
      lines.push('Apple Maps verán tus platos, precios y etiquetas dietéticas sin que');
      lines.push('hagas nada más.');
      lines.push('');
      lines.push('Adentro de la misma carpeta, **`menu-qr.png`** es un código QR de');
      lines.push('480 × 480 px apuntando a donde dijiste que viviría tu menú. Imprímelo');
      lines.push('a cualquier tamaño entre 2.5 cm y 15 cm — el QR tiene corrección de');
      lines.push('error integrada.');
    }
    if (hasJsonld) {
      lines.push('');
      lines.push('Si tu CMS solo acepta un snippet JSON-LD, **`' + ldName + '`** es el');
      lines.push('mismo grafo `Menu` como archivo independiente — pégalo dentro de un');
      lines.push('tag `<script type="application/ld+json">…</script>` en `<head>`.');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Para el staff');
    lines.push('');
    if (hasText) {
      lines.push('**`' + textName + '`** es el menú en texto plano — legible en');
      lines.push('cualquier cliente de email, cualquier teléfono, cualquier impresora.');
      lines.push('Útil como referencia de cocina, hoja para runners, o copia de buzón');
      lines.push('cuando el menú impreso está en el enmarcador.');
    }
    if (hasMd) {
      lines.push('');
      lines.push('**`' + mdName + '`** es el mismo contenido como Markdown — se pega');
      lines.push('en Notion, Slack, GitHub o tus documentos de entrenamiento sin');
      lines.push('perder la estructura.');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Guarda esta carpeta');
    lines.push('');
    lines.push('Pon el zip completo en una carpeta "Menús" en algún lugar seguro. La');
    lines.push('próxima vez que reimprimas, no tendrás que empezar de cero — tu');
    lines.push('imprenta puede re-correr el mismo PDF, y tu encargado de sitio puede');
    lines.push('re-pegar el mismo HTML.');
    lines.push('');
    lines.push('Cuando cambies un precio, re-abre la herramienta, edita y re-exporta');
    lines.push('este pack. Sobreescribirá los archivos viejos en tu carpeta de');
    lines.push('descargas si conservas el mismo nombre de negocio.');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('Hecho con ♥ por Muntin Digital · Silver Spring, MD · muntin.digital');
    return lines.join('\n');
  }

  // ---------- mailto template (printer) --------------------------
  function buildMailtoEN(opts) {
    var biz = opts.businessName || 'our restaurant';
    var pdfName = opts.pdfName || 'menu.pdf';
    var paper = opts.paperLabel || 'Letter (8.5 × 11 in)';
    var pages = opts.pageCount || '?';
    var lines = [];
    lines.push('Subject: Menu print job for ' + biz);
    lines.push('');
    lines.push('Hi —');
    lines.push('');
    lines.push('Attached is our menu in print-ready format.');
    lines.push('');
    lines.push('  • File:        ' + pdfName);
    lines.push('  • Paper:       ' + paper);
    lines.push('  • Page count:  ' + pages);
    lines.push('  • Bleed:       3 mm where supported');
    lines.push('  • Crop marks:  yes (visible at the corners)');
    lines.push('  • Color:       CMYK (please confirm)');
    lines.push('  • Paper stock: uncoated cream, 60–80 lb (~90–120 gsm) preferred');
    lines.push('');
    lines.push('Quantity needed: [tell us how many copies]');
    lines.push('Pickup or delivery: [your preference]');
    lines.push('When you need them by: [date]');
    lines.push('');
    lines.push('Please confirm receipt and let us know about any issues with the');
    lines.push('file before printing — we would rather catch a typo now than after');
    lines.push('the press run.');
    lines.push('');
    lines.push('Thanks,');
    lines.push(biz);
    return lines.join('\n');
  }

  function buildMailtoES(opts) {
    var biz = opts.businessName || 'nuestro restaurante';
    var pdfName = opts.pdfName || 'menu.pdf';
    var paper = opts.paperLabel || 'Carta (8.5 × 11 in)';
    var pages = opts.pageCount || '?';
    var lines = [];
    lines.push('Asunto: Trabajo de impresión de menú para ' + biz);
    lines.push('');
    lines.push('Hola —');
    lines.push('');
    lines.push('Adjunto va nuestro menú en formato listo para imprenta.');
    lines.push('');
    lines.push('  • Archivo:        ' + pdfName);
    lines.push('  • Papel:          ' + paper);
    lines.push('  • Páginas:        ' + pages);
    lines.push('  • Bleed:          3 mm donde aplica');
    lines.push('  • Marcas de corte: sí (visibles en las esquinas)');
    lines.push('  • Color:          CMYK (por favor confirmen)');
    lines.push('  • Stock de papel: uncoated crema, 60–80 lb (~90–120 gsm) preferible');
    lines.push('');
    lines.push('Cantidad: [cuántas copias]');
    lines.push('Entrega o recoger: [tu preferencia]');
    lines.push('Para cuándo: [fecha]');
    lines.push('');
    lines.push('Por favor confirmen recepción y avisen de cualquier problema con el');
    lines.push('archivo antes de imprimir — preferimos cazar un typo ahora que después');
    lines.push('de la corrida de imprenta.');
    lines.push('');
    lines.push('Gracias,');
    lines.push(biz);
    return lines.join('\n');
  }

  // ---------- manifest.json --------------------------------------
  // Machine-readable index of pack contents. A future "import this
  // pack" tool, a backup-restore flow, or an external integration
  // can read this without re-parsing the README.
  function buildManifest(opts, files) {
    return {
      v: 1,
      generatedAt: Date.now(),
      generator: 'muntin-menu-design-suite',
      generatorUrl: 'https://muntin.digital/tools/menu-design/',
      business: {
        name: opts.businessName || '',
        cuisine: opts.cuisine || '',
        locale: opts.locale || 'en'
      },
      menu: {
        sections: opts.sectionCount || 0,
        dishes: opts.dishCount || 0,
        allergenRegime: opts.allergenRegime || 'us-fda9'
      },
      theme: {
        id: opts.themeId || '',
        paper: opts.paperKey || ''
      },
      files: files.map(function (f) { return { name: f.name, kind: f.kind }; })
    };
  }

  // ---------- Pack assembly --------------------------------------
  /**
   * Compose a Menu Pack ZIP.
   *
   * @param {object} opts
   * @param {object} opts.canonicalMenu  v3 menu (or v2-shape; auto-migrates)
   * @param {Function} opts.loadJSZip    () → Promise<JSZip>; callers use the
   *                                      existing one in MD_HTML
   * @param {Function} [opts.exportPdf]  (opts) → Promise<Blob>; falls back
   *                                      to MD_PDF.exportPdf when present
   * @param {Function} [opts.exportQrZip] (opts) → Promise<Blob>; falls back
   *                                      to MD_HTML.exportZip
   * @param {Function} [opts.exportText] (opts) → string; falls back to
   *                                      MD_TEXT.exportPlainText
   * @param {Function} [opts.exportMd]   (opts) → string; falls back to
   *                                      MD_TEXT.exportMarkdown
   * @param {Function} [opts.emitJsonld] (menu, opts) → string; falls back to
   *                                      MD_JSONLD.emitInline
   * @param {object}   [opts.pdfOpts]    extra opts for PDF emitter
   * @param {object}   [opts.htmlOpts]   extra opts for HTML emitter
   * @param {object}   [opts.textOpts]   extra opts for text emitters
   * @param {string}   [opts.locale]     'en' | 'es'
   * @param {string}   [opts.businessName]
   * @param {string}   [opts.paperLabel]
   * @param {string}   [opts.cuisine]
   * @param {string}   [opts.themeId]
   * @param {string}   [opts.paperKey]
   * @param {string}   [opts.allergenRegime]
   * @returns {Promise<Blob>}
   */
  function exportPack(opts) {
    opts = opts || {};
    var locale = opts.locale || 'en';
    var menu = opts.canonicalMenu || null;
    var loadJSZip = opts.loadJSZip
      || (root && root.MD_HTML && root.MD_HTML.loadJsZip)
      || null;
    if (!loadJSZip) {
      return Promise.reject(new Error('Menu Pack: no JSZip loader available'));
    }
    if (!menu || !Array.isArray(menu.dishes)) {
      return Promise.reject(new Error('Menu Pack: canonicalMenu required (v3 shape)'));
    }

    var slug = makeSlug(opts.businessName || (menu.meta && menu.meta.businessName) || 'menu');
    var pdfName = slug + '.pdf';
    var ldName = 'menu.jsonld';
    var textName = 'menu.txt';
    var mdName = 'menu.md';
    var mailName = 'mailto-printer.txt';
    var qrFolder = 'qr-menu/';

    // Build the simple text artifacts upfront — these never fail.
    var jsonldBody = '';
    try {
      var emitJsonld = opts.emitJsonld
        || (root && root.MD_JSONLD && root.MD_JSONLD.emitInline)
        || null;
      if (emitJsonld) jsonldBody = emitJsonld(menu, { url: opts.publishUrl || '' });
    } catch (_) {}

    var textBody = '';
    var mdBody = '';
    try {
      var exportText = opts.exportText
        || (root && root.MD_TEXT && root.MD_TEXT.exportPlainText)
        || null;
      var exportMd = opts.exportMd
        || (root && root.MD_TEXT && root.MD_TEXT.exportMarkdown)
        || null;
      var textOptsBase = Object.assign({}, opts.textOpts || {}, {
        locale: locale,
        rows: _menuToRows(menu),
        title: opts.businessName || (menu.meta && menu.meta.businessName) || '',
        tagline: menu.meta && menu.meta.tagline || '',
        story: menu.meta && menu.meta.story || '',
        disclaimer: menu.meta && menu.meta.disclaimer || ''
      });
      if (exportText) textBody = exportText(textOptsBase);
      if (exportMd)   mdBody   = exportMd(textOptsBase);
    } catch (_) {}

    // Track what actually shipped so the README and manifest are honest.
    var includes = {
      pdf:       !!opts.exportPdf || !!(root && root.MD_PDF && root.MD_PDF.exportPdf),
      qr:        !!opts.exportQrZip || !!(root && root.MD_HTML && root.MD_HTML.exportZip),
      jsonld:    !!jsonldBody,
      text:      !!textBody,
      markdown:  !!mdBody,
      mailto:    true
    };

    var readmeOpts = {
      businessName:  opts.businessName || (menu.meta && menu.meta.businessName) || '',
      includePdf:    includes.pdf,
      includeQr:     includes.qr,
      includeJsonld: includes.jsonld,
      includeText:   includes.text,
      includeMarkdown: includes.markdown,
      includeMailto: includes.mailto,
      pdfName:       pdfName,
      qrFolder:      qrFolder,
      jsonldName:    ldName,
      textName:      textName,
      mdName:        mdName,
      mailtoName:    mailName
    };
    var readmeBody = (locale === 'es')
      ? buildReadmeES(readmeOpts)
      : buildReadmeEN(readmeOpts);

    var mailtoOpts = {
      businessName: readmeOpts.businessName,
      pdfName:      pdfName,
      paperLabel:   opts.paperLabel || '',
      pageCount:    opts.pageCount || ''
    };
    var mailtoBody = (locale === 'es')
      ? buildMailtoES(mailtoOpts)
      : buildMailtoEN(mailtoOpts);

    var files = [
      { name: 'README.md',      kind: 'guide',     body: readmeBody, mime: 'text/markdown' },
      { name: mailName,         kind: 'mailto',    body: mailtoBody, mime: 'text/plain' }
    ];
    if (textBody)   files.push({ name: textName, kind: 'text',     body: textBody,   mime: 'text/plain' });
    if (mdBody)     files.push({ name: mdName,   kind: 'markdown', body: mdBody,     mime: 'text/markdown' });
    if (jsonldBody) files.push({ name: ldName,   kind: 'jsonld',   body: jsonldBody, mime: 'application/ld+json' });

    var manifest = buildManifest({
      businessName:    readmeOpts.businessName,
      cuisine:         opts.cuisine || (menu.meta && menu.meta.cuisine) || '',
      locale:          locale,
      sectionCount:    (menu.sections || []).length,
      dishCount:       (menu.dishes || []).length,
      allergenRegime:  opts.allergenRegime || (menu.meta && menu.meta.allergenRegime) || 'us-fda9',
      themeId:         opts.themeId || (menu.theme && menu.theme.id) || '',
      paperKey:        opts.paperKey || ''
    }, files.concat(includes.pdf ? [{ name: pdfName, kind: 'pdf' }] : [])
        .concat(includes.qr ? [{ name: qrFolder + 'index.html', kind: 'html' }, { name: qrFolder + 'menu-qr.png', kind: 'image' }] : []));
    files.push({
      name: 'manifest.json',
      kind: 'manifest',
      body: JSON.stringify(manifest, null, 2),
      mime: 'application/json'
    });

    // Build the ZIP.
    return loadJSZip().then(function (JSZip) {
      var zip = new JSZip();
      files.forEach(function (f) {
        zip.file(f.name, f.body);
      });

      // Pull in the PDF if available. Lazy + best-effort.
      var pdfPromise = Promise.resolve(null);
      if (includes.pdf) {
        var exportPdf = opts.exportPdf || (root && root.MD_PDF && root.MD_PDF.exportPdf);
        if (exportPdf) {
          var pdfOpts = Object.assign({}, opts.pdfOpts || {}, {
            rows:        _menuToRows(menu),
            theme:       opts.theme || null,
            paperKey:    opts.paperKey || (opts.pdfOpts && opts.pdfOpts.paperKey) || 'letter',
            customDims:  opts.customDims || null,
            title:       readmeOpts.businessName || 'Menu',
            tagline:     menu.meta && menu.meta.tagline || '',
            story:       menu.meta && menu.meta.story || '',
            footer: {
              address:       menu.meta && menu.meta.address       || '',
              hours:         menu.meta && menu.meta.hours         || '',
              serviceCharge: menu.meta && menu.meta.serviceCharge || '',
              sourcing:      menu.meta && menu.meta.sourcing      || '',
              disclaimer:    menu.meta && menu.meta.disclaimer    || '',
              askYourServer: menu.meta && menu.meta.askYourServer || ''
            },
            logoDataUrl: opts.logoDataUrl || '',
            logoMeta:    opts.logoMeta || null,
            locale:      locale,
            filename:    pdfName.replace(/\.pdf$/i, '')
          });
          pdfPromise = exportPdf(pdfOpts).then(function (pdfBlob) {
            // exportPdf may return { blob } or a raw Blob; handle both.
            var blob = pdfBlob && pdfBlob.blob ? pdfBlob.blob : pdfBlob;
            if (blob) zip.file(pdfName, blob);
          }).catch(function () { /* swallow; the rest still ships */ });
        }
      }

      // Pull in the QR-menu HTML+PNG if available.
      var qrPromise = Promise.resolve(null);
      if (includes.qr) {
        var exportQrZip = opts.exportQrZip || (root && root.MD_HTML && root.MD_HTML.exportZip);
        if (exportQrZip) {
          var htmlOpts = Object.assign({}, opts.htmlOpts || {}, {
            rows:        _menuToRows(menu),
            theme:       opts.theme || null,
            title:       readmeOpts.businessName || 'Menu',
            locale:      locale,
            logoDataUrl: opts.logoDataUrl || '',
            targetUrl:   opts.publishUrl || '',
            disclaimer:  menu.meta && menu.meta.disclaimer || '',
            canonicalMenu: menu,
            meta: {
              businessName:    readmeOpts.businessName,
              tagline:         menu.meta && menu.meta.tagline || '',
              cuisine:         menu.meta && menu.meta.cuisine || '',
              currency:        menu.meta && menu.meta.currency || 'USD',
              locale:          locale,
              allergenRegime:  manifest.menu.allergenRegime
            }
          });
          qrPromise = exportQrZip(htmlOpts).then(function (zipBlob) {
            // Unwrap the QR-menu zip into the qr-menu/ subfolder.
            return JSZip.loadAsync(zipBlob).then(function (innerZip) {
              var entries = [];
              innerZip.forEach(function (relPath, file) {
                if (!file.dir) entries.push({ relPath: relPath, file: file });
              });
              return Promise.all(entries.map(function (e) {
                return e.file.async(/^.+\.png$/.test(e.relPath) ? 'uint8array' : 'string')
                  .then(function (data) {
                    zip.file(qrFolder + e.relPath, data);
                  });
              }));
            });
          }).catch(function () { /* swallow */ });
        }
      }

      return Promise.all([pdfPromise, qrPromise]).then(function () {
        return zip.generateAsync({ type: 'blob' });
      });
    });
  }

  // ---------- v3 → row-stream (for emitters that take v2 shape) -----
  function _menuToRows(menu) {
    var rows = [];
    var sections = (menu.sections || []).slice().sort(function (a, b) {
      return (a.position || 0) - (b.position || 0);
    });
    var dishesBySection = {};
    (menu.dishes || []).forEach(function (d) {
      (dishesBySection[d.sectionId] = dishesBySection[d.sectionId] || []).push(d);
    });
    sections.forEach(function (s) {
      if (s.name) rows.push({ kind: 'section', name: s.name });
      var ds = (dishesBySection[s.id] || []).slice().sort(function (a, b) {
        return (a.position || 0) - (b.position || 0);
      });
      ds.forEach(function (d) {
        rows.push({
          kind:      'dish',
          name:      d.name || '',
          price:     d.price || '',
          desc:      d.desc || '',
          allergens: (d.allergens || []).slice(),
          spice:     d.spice || 0,
          badges:    (d.badges || []).slice(),
          photo:     d.photo || null
        });
      });
    });
    return rows;
  }

  // ---------- Bilingual pack composer ------------------------------
  // Wave studio-quality — one click → both languages, all artifacts.
  //
  // Bilingual operators (DMV-area Latino restaurants, hotel F&B, etc.)
  // hand the EN PDF to one cook line and the ES PDF to the other, the
  // EN README to their print shop and the ES README to their bilingual
  // staff. Without this they ran the export twice and renamed files
  // by hand. With this they get one zip with en/ and es/ subfolders.
  //
  // Implementation: runs exportPack() per locale then merges into a
  // parent zip. The shipped artifacts (README, mailto, allergen
  // disclaimer text) are locale-aware; the dish content stays as the
  // operator typed it (we don't translate names or descriptions).
  //
  // @param {object} opts            same as exportPack (sans `locale`)
  // @param {string[]} [locales]     defaults to ['en', 'es']
  // @returns {Promise<Blob>}
  function exportBilingualPack(opts, locales) {
    opts = opts || {};
    locales = (Array.isArray(locales) && locales.length) ? locales : ['en', 'es'];
    var loadJSZip = opts.loadJSZip
      || (root && root.MD_HTML && root.MD_HTML.loadJsZip)
      || null;
    if (!loadJSZip) {
      return Promise.reject(new Error('Bilingual Menu Pack: no JSZip loader available'));
    }
    var perLocaleBlobs = [];
    var chain = Promise.resolve();
    locales.forEach(function (loc) {
      chain = chain.then(function () {
        var perOpts = Object.assign({}, opts, { locale: loc });
        return exportPack(perOpts).then(function (blob) {
          perLocaleBlobs.push({ locale: loc, blob: blob });
        });
      });
    });
    return chain.then(function () {
      return loadJSZip().then(function (JSZip) {
        var parent = new JSZip();
        // Top-level README orienting the operator to the two folders.
        var biz = opts.businessName || 'your restaurant';
        var when = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
        var topReadme =
          '# Bilingual menu pack — ' + biz + '\n' +
          'Generated: ' + when + '\n\n' +
          'This pack ships your menu in ' + locales.length + ' languages, side by side.\n' +
          'Each subfolder is a complete pack — open the README inside for handoff guidance.\n\n' +
          locales.map(function (l) {
            var name = l === 'es' ? 'Spanish (ES)' : (l === 'en' ? 'English (EN)' : l.toUpperCase());
            return '- `' + l + '/` — ' + name + ' artifacts (PDF, QR menu, JSON-LD, plain text + Markdown, mailto template)';
          }).join('\n') +
          '\n\n## Why both languages\n' +
          'Your bilingual staff can read the disclaimer in their language; your print shop and web dev get the same in theirs. Allergen labels, regulatory disclaimer, and the README are all translated. Dish names and descriptions stay exactly as you wrote them.\n\n' +
          '## Privacy\n' +
          'Both packs were generated in your browser. Nothing was uploaded.\n';
        parent.file('README.md', topReadme);
        // Unpack each per-locale zip into a subfolder.
        var unpackChain = Promise.resolve();
        perLocaleBlobs.forEach(function (entry) {
          unpackChain = unpackChain.then(function () {
            return JSZip.loadAsync(entry.blob).then(function (innerZip) {
              var entries = [];
              innerZip.forEach(function (relPath, file) {
                if (!file.dir) entries.push({ relPath: relPath, file: file });
              });
              return Promise.all(entries.map(function (e) {
                var asType = /\.(pdf|png|jpg|jpeg|webp)$/i.test(e.relPath) ? 'uint8array' : 'string';
                return e.file.async(asType).then(function (data) {
                  parent.file(entry.locale + '/' + e.relPath, data);
                });
              }));
            });
          });
        });
        return unpackChain.then(function () {
          return parent.generateAsync({ type: 'blob' });
        });
      });
    });
  }

  var api = {
    exportPack:          exportPack,
    exportBilingualPack: exportBilingualPack,
    // exported for tests
    _buildReadmeEN:  buildReadmeEN,
    _buildReadmeES:  buildReadmeES,
    _buildMailtoEN:  buildMailtoEN,
    _buildMailtoES:  buildMailtoES,
    _buildManifest:  buildManifest,
    _menuToRows:     _menuToRows,
    _makeSlug:       makeSlug
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (root) root.MD_PACK = api;
})(typeof window !== 'undefined' ? window : null);
