#!/usr/bin/env python3
"""Second-pass SEO enrichment. Adds six structured-data + head-tag
improvements across every published + staged page on both locales.

Done
----
1. <meta name="robots" content="max-image-preview:large, max-snippet:-1,
   max-video-preview:-1"> injected on non-noindex pages. Tells Google to
   pull the full snippet + hero image into SERP results (most sites omit
   these directives and get truncated previews).

2. <link rel="preconnect"> for plausible.io added to <head> before
   the analytics script tag. Saves 100\u2013300 ms on first external
   request \u2014 indirect ranking signal via Core Web Vitals. (The
   Window is same-origin, so no preconnect needed.)

3. JSON-LD `author` promoted from inline Person to a referenced @id
   ({ "@id": "https://muntin.digital/about/#don-goldstein" }). The canonical
   Person node is defined once on the homepage + about page, every
   BlogPosting just points at it. Single source of truth for E-E-A-T
   author signals, fewer duplicate entities in structured data.

4. `AudioObject` added to the @graph of every post with an audio.mp3
   alongside the existing `speakable`. Declares the narration as an
   indexable audio asset (voice-assistant / Google Assistant discovery).

5. `image` promoted from URL string to full `ImageObject`
   ({ url, width: 1200, height: 630, caption }). Richer Article cards.

6. `mainEntityOfPage` promoted from URL string to full `WebPage` node
   ({ "@id": ".../#webpage", url, name, isPartOf: { "@id": ".../#website" } }).
   Clearer page-level entity for crawlers + GSC.

Safe to re-run. The script detects existing markers and JSON-LD fields
before touching anything.

Usage
-----
  python3 scripts/enrich-post-seo-v2.py [--check]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHECK_ONLY = "--check" in sys.argv

PERSON_ID = "https://muntin.digital/about/#don-goldstein"
BUSINESS_ID = "https://muntin.digital/#business"
WEBSITE_ID = "https://muntin.digital/#website"

# 1. Robots directives --------------------------------------------------------
ROBOTS_PROGRESSIVE = (
    '<meta name="robots" content="max-image-preview:large, '
    'max-snippet:-1, max-video-preview:-1" />'
)
ROBOTS_MARKER_RE = re.compile(
    r'<meta name="robots" content="max-image-preview:large[^"]*"\s*/?>'
)
NOINDEX_RE = re.compile(
    r'<meta name="robots" content="noindex', re.IGNORECASE
)


def patch_robots(html: str) -> str:
    if NOINDEX_RE.search(html):
        return html  # noindex supersedes; don't stack extra directives
    if ROBOTS_MARKER_RE.search(html):
        return html  # already patched
    # Insert after <meta charset> + <meta viewport>; sits right above title.
    viewport_re = re.compile(
        r'(<meta name="viewport"[^>]*/?>\s*\n)'
    )
    if viewport_re.search(html):
        return viewport_re.sub(
            lambda m: m.group(1) + ROBOTS_PROGRESSIVE + "\n", html, count=1
        )
    return html


# 2. Preconnect hints ---------------------------------------------------------
# Phase W.8 (The Window) — Calendly hints removed. The Window is
# served same-origin via /window/, so no third-party connection
# warmup is needed. Plausible stays.
PRECONNECT_BLOCK = (
    '<!-- i18n:preconnect START (generated by scripts/enrich-post-seo-v2.py) -->\n'
    '<link rel="preconnect" href="https://plausible.io" crossorigin />\n'
    '<link rel="dns-prefetch" href="https://plausible.io" />\n'
    '<!-- i18n:preconnect END -->\n'
)
PRECONNECT_BLOCK_RE = re.compile(
    r'<!-- i18n:preconnect START[\s\S]*?<!-- i18n:preconnect END -->\n?'
)


def patch_preconnect(html: str) -> str:
    # Only add on pages that actually load Plausible (every site page does)
    # or link to Calendly (most pages do via nav/footer).
    if 'plausible.io' not in html:
        return html
    new_block = PRECONNECT_BLOCK
    if PRECONNECT_BLOCK_RE.search(html):
        return PRECONNECT_BLOCK_RE.sub(new_block, html)
    # Insert right before the first <script ... plausible.io ...>.
    plausible_re = re.compile(r'(<script[^>]+plausible\.io[^>]*></script>)')
    m = plausible_re.search(html)
    if m:
        return html[: m.start()] + new_block + html[m.start() :]
    return html


# 3-6. JSON-LD enrichment -----------------------------------------------------
def _image_object(url: str, caption: str | None) -> dict:
    d = {
        "@type": "ImageObject",
        "url": url,
        "width": 1200,
        "height": 630,
    }
    if caption:
        d["caption"] = caption
    return d


def _webpage_node(url: str, name: str) -> dict:
    return {
        "@type": "WebPage",
        "@id": url + "#webpage",
        "url": url,
        "name": name,
        "isPartOf": {"@id": WEBSITE_ID},
    }


def _audio_object(post_url: str, headline: str, language: str) -> dict:
    return {
        "@type": "AudioObject",
        "@id": post_url + "#audio",
        "contentUrl": post_url + "audio.mp3",
        "encodingFormat": "audio/mpeg",
        "inLanguage": language,
        "name": f"{headline} \u2014 audio narration",
        "description": (
            "Full article read aloud by Don. Also available in Spanish, "
            "French, Italian, Portuguese, and Chinese."
        ),
        "associatedArticle": {"@id": post_url + "#article"},
    }


def patch_jsonld(html: str, slug: str, is_draft: bool, is_es: bool) -> str:
    """Rewrite the BlogPosting graph for structural richness."""
    script_re = re.compile(
        r'(<script type="application/ld\+json">\s*)([\s\S]*?)(\s*</script>)',
        re.IGNORECASE,
    )
    match = script_re.search(html)
    if not match:
        return html
    try:
        data = json.loads(match.group(2))
    except json.JSONDecodeError:
        return html

    graph = data.get("@graph")
    if not isinstance(graph, list):
        return html

    en_slug_root = f"https://muntin.digital/{'es/' if is_es else ''}blog/"
    if is_draft:
        en_slug_root += "drafts/"
    post_url = en_slug_root + slug + "/"

    changed = False
    blog_posting = None
    for node in graph:
        if not isinstance(node, dict):
            continue
        # Older posts use BlogPosting; newer ones (May-2026 publication
        # wave onward, scaffolded by new-article-skeleton.mjs) use
        # Article. Both are valid Schema.org Post types and both get
        # the same enrichments (AudioObject, ImageObject, mainEntityOfPage,
        # author @id reference). Without this, every Article-typed post
        # silently shipped without these schemas.
        if node.get("@type") not in ("BlogPosting", "Article"):
            continue
        blog_posting = node

        headline = node.get("headline", "")
        image_url = node.get("image") if isinstance(node.get("image"), str) else None
        if not image_url and isinstance(node.get("image"), dict):
            image_url = node["image"].get("url")

        # 5. image -> ImageObject
        if isinstance(node.get("image"), str):
            node["image"] = _image_object(node["image"], headline)
            changed = True

        # 6. mainEntityOfPage -> WebPage node
        if isinstance(node.get("mainEntityOfPage"), str):
            node["mainEntityOfPage"] = _webpage_node(post_url, headline)
            changed = True

        # 3. author -> @id reference (canonical Person lives on homepage/about)
        if isinstance(node.get("author"), dict) and "@id" not in node["author"]:
            node["author"] = {"@id": PERSON_ID}
            changed = True

    # 4. AudioObject — append as sibling if a listen-btn is present on page
    has_audio = 'listen-btn' in html and 'data-audio-src' in html
    already_has_audio = any(
        isinstance(n, dict) and n.get("@type") == "AudioObject" for n in graph
    )
    if has_audio and not already_has_audio and blog_posting is not None:
        lang = "en-US" if not is_es else "es"
        audio_node = _audio_object(
            post_url, blog_posting.get("headline", ""), lang
        )
        # Insert right after BlogPosting for readability.
        idx = graph.index(blog_posting) + 1
        graph.insert(idx, audio_node)
        # Link BlogPosting -> AudioObject.
        blog_posting["audio"] = {"@id": audio_node["@id"]}
        changed = True

    if not changed:
        return html
    new_block = json.dumps(data, indent=2, ensure_ascii=False)
    return html[: match.start(2)] + new_block + html[match.end(2) :]


# Canonical Person entity -----------------------------------------------------
def _person_node() -> dict:
    return {
        "@type": "Person",
        "@id": PERSON_ID,
        "name": "Don Goldstein",
        "givenName": "Don",
        "familyName": "Goldstein",
        "jobTitle": "Founder, Muntin Digital",
        "worksFor": {"@id": BUSINESS_ID},
        "url": "https://muntin.digital/about/",
        "sameAs": [
            "https://www.instagram.com/muntin.digital/",
        ],
        "knowsAbout": [
            "Restaurant website design",
            "Small business SEO",
            "Google Business Profile",
            "Restaurant operations",
            "Website conversion optimization",
        ],
    }


def ensure_person_on_homepage(html: str) -> str:
    """Add the canonical Person node to the homepage + about page @graph."""
    script_re = re.compile(
        r'(<script type="application/ld\+json">\s*)([\s\S]*?)(\s*</script>)',
        re.IGNORECASE,
    )
    match = script_re.search(html)
    if not match:
        return html
    try:
        data = json.loads(match.group(2))
    except json.JSONDecodeError:
        return html
    graph = data.get("@graph")
    if not isinstance(graph, list):
        return html
    if any(
        isinstance(n, dict) and n.get("@id") == PERSON_ID for n in graph
    ):
        return html
    graph.append(_person_node())
    new_block = json.dumps(data, indent=2, ensure_ascii=False)
    return html[: match.start(2)] + new_block + html[match.end(2) :]


# -----------------------------------------------------------------------------
def _slug_info(path: Path) -> tuple[str, bool, bool]:
    parts = path.parts
    is_draft = "drafts" in parts
    is_es = "es" in parts[: parts.index("blog") + 1] if "blog" in parts else False
    slug = path.parent.name
    return slug, is_draft, is_es


def process(path: Path) -> bool:
    html = path.read_text(encoding="utf-8")
    orig = html

    # 1 + 2: every page (not just blog).
    html = patch_robots(html)
    html = patch_preconnect(html)

    # 3-6: only blog posts (has a BlogPosting @graph node).
    if path.parent.name != path.parent.parent.name and "blog" in path.parts:
        parts = path.parts
        if "blog" in parts and path.parent.name not in ("blog", "drafts"):
            slug, is_draft, is_es = _slug_info(path)
            html = patch_jsonld(html, slug, is_draft, is_es)

    # Canonical Person on the two pages that should host it.
    rel = path.relative_to(REPO).as_posix()
    if rel in ("index.html", "about/index.html", "es/index.html", "es/about/index.html"):
        html = ensure_person_on_homepage(html)

    if html == orig:
        return False
    if CHECK_ONLY:
        print(f"  would update: {path.relative_to(REPO)}")
        return True
    path.write_text(html, encoding="utf-8")
    print(f"  updated: {path.relative_to(REPO)}")
    return True


def main():
    roots = [REPO]
    changed = 0
    total = 0
    # Walk every HTML file, but exclude tooling + static dirs.
    EXCLUDE = {"node_modules", ".git", "dist", ".wrangler", "_includes",
               "brand", "scripts", "assets"}
    for html in REPO.rglob("*.html"):
        if any(p in EXCLUDE for p in html.parts):
            continue
        total += 1
        if process(html):
            changed += 1
    print(f"\n{'would update' if CHECK_ONLY else 'updated'} {changed}/{total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
