#!/usr/bin/env python3
"""Third-pass SEO enrichment. Closes four discovery-and-richness gaps
that v1 + v2 left open, applied as cross-cutting <head> additions
across every published + staged page on both locales.

Done
----
1. RSS feed discovery — every page now carries
   <link rel="alternate" type="application/rss+xml" title="..."
         href="/feed.xml"> in <head>. v1/v2 left RSS as a footer
   text link only, which feed readers and crawlers don't see. Per
   locale: EN pages point at /feed.xml, ES pages point at
   /es/feed.xml. Modern feed readers (NetNewsWire, Feedly, RSS
   apps, and the Edge browser's RSS extensions) all probe the
   document <head> for this <link>; the footer anchor isn't a
   discovery surface.

2. AI/LLM feed discovery — every EN page now carries
   <link rel="alternate" type="application/feed+json"
         title="Muntin Digital — LLM feed" href="/feed-llm.json">
   This advertises the JSON-flavored feed-llm.json that lives at
   the root. /es/ has no feed-llm.json so the link is EN-only.

3. Article authorship signal — pages whose JSON-LD declares a
   BlogPosting or Article get <meta name="author" content="..."> +
   the corresponding article:author OpenGraph property if it's
   missing. Already-present author tags are left alone (idempotent).

4. Article freshness signal — pages whose JSON-LD declares a
   BlogPosting/Article with a `dateModified` get
   <meta property="article:modified_time" content="..."> if it isn't
   already there. This is the OG/SEO sister to the JSON-LD
   `dateModified`; Facebook, LinkedIn, and other crawlers use the
   meta tag while Google reads either.

Safe to re-run. Each block is wrapped in a sentinel comment
(`<!-- seo-v3:feed START -->`, `<!-- seo-v3:article-meta START -->`)
so the script detects its own work before touching anything.

Usage
-----
  python3 scripts/enrich-post-seo-v3.py [--check]

Pairs with enrich-post-seo.py (v1) and enrich-post-seo-v2.py (v2);
all three are idempotent and order-independent.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHECK_ONLY = "--check" in sys.argv

NOINDEX_RE = re.compile(
    r'<meta name="robots" content="noindex', re.IGNORECASE
)

# 1 + 2. Feed-discovery <link rel="alternate"> ------------------------------
FEED_BLOCK_RE = re.compile(
    r'\n?<!-- seo-v3:feed START[\s\S]*?<!-- seo-v3:feed END -->\n?'
)


def feed_block(is_es: bool) -> str:
    """Return the <head> block that advertises the RSS + JSON feeds.

    EN pages point at the root /feed.xml + /feed-llm.json.
    ES pages point at /es/feed.xml only; no /es/feed-llm.json exists.
    """
    if is_es:
        return (
            "\n<!-- seo-v3:feed START (generated by scripts/enrich-post-seo-v3.py) -->\n"
            '<link rel="alternate" type="application/rss+xml" '
            'title="Muntin Digital — Artículos" href="/es/feed.xml" />\n'
            "<!-- seo-v3:feed END -->\n"
        )
    return (
        "\n<!-- seo-v3:feed START (generated by scripts/enrich-post-seo-v3.py) -->\n"
        '<link rel="alternate" type="application/rss+xml" '
        'title="Muntin Digital — Articles" href="/feed.xml" />\n'
        '<link rel="alternate" type="application/feed+json" '
        'title="Muntin Digital — LLM feed" href="/feed-llm.json" />\n'
        "<!-- seo-v3:feed END -->\n"
    )


def patch_feeds(html: str, is_es: bool) -> str:
    new_block = feed_block(is_es)
    if FEED_BLOCK_RE.search(html):
        return FEED_BLOCK_RE.sub(new_block, html, count=1)
    # Insert right after the i18n:hreflang END block when present, else
    # before the first <meta property="og: line. Both anchors are stable
    # across the codebase.
    hreflang_end_re = re.compile(r'(<!-- i18n:hreflang END -->\n)')
    m = hreflang_end_re.search(html)
    if m:
        return html[: m.end()] + new_block + html[m.end():]
    og_re = re.compile(r'(\n<meta property="og:)')
    m = og_re.search(html)
    if m:
        return html[: m.start()] + new_block + html[m.start():]
    return html


# 3 + 4. Article-page meta ---------------------------------------------------
ARTICLE_META_BLOCK_RE = re.compile(
    r'\n?<!-- seo-v3:article-meta START[\s\S]*?<!-- seo-v3:article-meta END -->\n?'
)

AUTHOR_META_RE = re.compile(
    r'<meta name="author"[^>]*>', re.IGNORECASE
)
ARTICLE_AUTHOR_OG_RE = re.compile(
    r'<meta property="article:author"[^>]*>', re.IGNORECASE
)
ARTICLE_MODIFIED_OG_RE = re.compile(
    r'<meta property="article:modified_time"[^>]*>', re.IGNORECASE
)


def _extract_article_node(graph_or_dict) -> dict | None:
    """Find the first Article/BlogPosting/NewsArticle node in a JSON-LD payload."""
    candidates = []
    if isinstance(graph_or_dict, list):
        candidates = graph_or_dict
    elif isinstance(graph_or_dict, dict):
        if isinstance(graph_or_dict.get("@graph"), list):
            candidates = graph_or_dict["@graph"]
        else:
            candidates = [graph_or_dict]
    for node in candidates:
        if not isinstance(node, dict):
            continue
        t = node.get("@type")
        if isinstance(t, list):
            if any(x in ("Article", "BlogPosting", "NewsArticle") for x in t):
                return node
        elif t in ("Article", "BlogPosting", "NewsArticle"):
            return node
    return None


def _resolve_author_name(node: dict, all_nodes: list) -> str | None:
    """Return the author's display name. Resolves @id references."""
    author = node.get("author")
    if not author:
        return None
    if isinstance(author, dict):
        if isinstance(author.get("name"), str):
            return author["name"]
        ref = author.get("@id")
        if ref and isinstance(all_nodes, list):
            for n in all_nodes:
                if isinstance(n, dict) and n.get("@id") == ref:
                    if isinstance(n.get("name"), str):
                        return n["name"]
        # Canonical Person on this site is don-goldstein. If the ref
        # matches the well-known ID but the node isn't inlined here,
        # fall back to the known display name rather than skip the
        # author meta tag entirely.
        if ref and "don-goldstein" in ref:
            return "Don Goldstein"
    return None


def patch_article_meta(html: str) -> str:
    """Add author + modified_time meta tags derived from JSON-LD.

    Idempotency strategy: strip any prior sentinel block from a working
    copy before scanning for existing tags. Otherwise pass N+1 sees the
    tags we wrote on pass N, decides no additions are needed, and
    deletes the block — flapping forever.
    """
    # Work against a copy with any prior sentinel block removed, so we
    # only detect author / modified_time meta tags from outside our
    # managed region.
    bare_html = ARTICLE_META_BLOCK_RE.sub("\n", html, count=1)

    # Find every JSON-LD script and look for an Article node anywhere.
    script_re = re.compile(
        r'<script type="application/ld\+json">\s*([\s\S]*?)\s*</script>',
        re.IGNORECASE,
    )
    article = None
    flat_nodes: list = []
    for m in script_re.finditer(bare_html):
        try:
            data = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        # Flatten nodes across all JSON-LD blocks for @id resolution.
        if isinstance(data, list):
            flat_nodes.extend([x for x in data if isinstance(x, dict)])
        elif isinstance(data, dict):
            if isinstance(data.get("@graph"), list):
                flat_nodes.extend(
                    [x for x in data["@graph"] if isinstance(x, dict)]
                )
            else:
                flat_nodes.append(data)
        candidate = _extract_article_node(data)
        if candidate and article is None:
            article = candidate
    if article is None:
        return html

    author_name = _resolve_author_name(article, flat_nodes)
    date_modified = article.get("dateModified")
    if isinstance(date_modified, dict):
        date_modified = None  # only accept plain string

    additions = []

    if author_name and not AUTHOR_META_RE.search(bare_html):
        additions.append(
            f'<meta name="author" content="{_escape_attr(author_name)}" />'
        )

    # If article:author OG isn't present but we have the name, add it.
    if author_name and not ARTICLE_AUTHOR_OG_RE.search(bare_html):
        additions.append(
            f'<meta property="article:author" '
            f'content="{_escape_attr(author_name)}" />'
        )

    if date_modified and not ARTICLE_MODIFIED_OG_RE.search(bare_html):
        additions.append(
            f'<meta property="article:modified_time" '
            f'content="{_escape_attr(date_modified)}" />'
        )

    if not additions:
        # No tags to add. Strip a stale managed block if present so
        # head stays clean (only safe because we just verified all the
        # tags exist outside our region).
        if ARTICLE_META_BLOCK_RE.search(html):
            return ARTICLE_META_BLOCK_RE.sub("\n", html, count=1)
        return html

    new_block = (
        "\n<!-- seo-v3:article-meta START (generated by scripts/enrich-post-seo-v3.py) -->\n"
        + "\n".join(additions)
        + "\n<!-- seo-v3:article-meta END -->\n"
    )

    if ARTICLE_META_BLOCK_RE.search(html):
        return ARTICLE_META_BLOCK_RE.sub(new_block, html, count=1)

    # Anchor: right before the JSON-LD <script>, or right before </head>.
    script_anchor_re = re.compile(r'(\n<script type="application/ld\+json">)')
    m = script_anchor_re.search(html)
    if m:
        return html[: m.start()] + new_block.rstrip("\n") + html[m.start():]
    head_close_re = re.compile(r'(</head>)', re.IGNORECASE)
    m = head_close_re.search(html)
    if m:
        return html[: m.start()] + new_block + html[m.start():]
    return html


def _escape_attr(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


# -----------------------------------------------------------------------------
def is_es_page(path: Path) -> bool:
    return "es" in path.parts[:2] or (
        len(path.parts) > 1 and path.parts[0] == "es"
    )


def process(path: Path) -> bool:
    html = path.read_text(encoding="utf-8")
    orig = html

    try:
        rel_parts = path.resolve().relative_to(REPO).parts
    except ValueError:
        rel_parts = path.parts
    is_es = bool(rel_parts) and rel_parts[0] == "es"

    # Skip noindex pages — no point advertising feeds or article meta
    # from a page that's explicitly excluded from search results. The
    # 404 page, account, admin, sign-in, workbench, drafts, and the
    # destructive-action confirmation surfaces all carry noindex and
    # would only pollute the head with no benefit.
    if NOINDEX_RE.search(html):
        return False

    # Skip pages that aren't real <head>+<body> documents (the brand
    # OG preview is a stand-alone artifact, not a site page).
    if "<head" not in html.lower():
        return False

    html = patch_feeds(html, is_es)
    html = patch_article_meta(html)

    if html == orig:
        return False
    if CHECK_ONLY:
        print(f"  would update: {path.relative_to(REPO)}")
        return True
    path.write_text(html, encoding="utf-8")
    print(f"  updated: {path.relative_to(REPO)}")
    return True


def main():
    changed = 0
    total = 0
    EXCLUDE = {
        "node_modules",
        ".git",
        "dist",
        ".wrangler",
        "_includes",
        "brand",
        "scripts",
        "assets",
        "tests",
        "src",
        "data",
    }
    for html in REPO.rglob("*.html"):
        if any(p in EXCLUDE for p in html.parts):
            continue
        total += 1
        if process(html):
            changed += 1
    print(f"\n{'would update' if CHECK_ONLY else 'updated'} {changed}/{total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
